export const FETCH_BUDGETS = "FETCH_BUDGET";
export const FETCH_BUDGET = "FETCH_BUDGET";
export const ADD_BUDGET = "CREATE_BUDGET";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";
