export const FETCH_MEETINGS = 'FETCH_MEETINGS'
export const FETCH_MEETING = 'FETCH_MEETING'
export const ADD_MEETING = 'ADD_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const DELETE_MEETING = 'DELETE_MEETING'

